Repository FESP01-TodoApp-Project10/FESP01-TodoApp-Project10, pull requests merged in 2023-11, with the labels that each got.

#1 feat: 등록 기능vanilaJS => React로 변경
  03.react/src/component/common/Header.tsx
  03.react/src/pages/registPage/TodoRegist.tsx
  03.react/src/pages/registPage/TodoRegistSettings.ts
  03.react/src/todoapp.d.ts
Labels: 1️⃣TEAM, 2️⃣TEAM, 💻Feature, ✨Refactor

#2 feat : 메인 및 상세 조회, 수정, 삭제
  03.react/package-lock.json
  03.react/package.json
  03.react/src/component/updatePage/TodoUpdate.ts
  03.react/src/component/updatePage/TodoUpdate.tsx
  03.react/src/pages/mainPage/TodoListMain.tsx
  package-lock.json
Labels: 1️⃣TEAM, 2️⃣TEAM, 💻Feature, ✨Refactor

#3 Style : 메인 페이지 스타일링 추가
  03.react/src/component/common/Footer.tsx
  03.react/src/component/common/Header.tsx
  03.react/src/component/updatePage/TodoUpdate.tsx
  03.react/src/pages/mainPage/TodoListMain.tsx
Labels: 1️⃣TEAM, 2️⃣TEAM, 💻Fix, 💻Feature

#5 react-feat/css css 수정, 일부 코드 추가 및 README 작성
  03.react/public/favicon.ico
  03.react/public/index.html
  03.react/public/logo192.png
  03.react/public/logo512.png
  03.react/src/component/common/Header.tsx
  03.react/src/component/updatePage/TodoUpdate.tsx
  03.react/src/pages/mainPage/TodoListMain.tsx
  03.react/src/pages/registPage/TodoRegist.css
  03.react/src/pages/registPage/TodoRegist.tsx
  README.md
  todo.png
  todoRegist.png
Labels: 📑Docs, 💻Fix

#6 docs: README 최종 수정
  03.react/START.md
  README.md
Labels: 📑Docs

#7 docs: README
  README.md
Labels: 📑Docs
